import AppKit
import Carbon

@MainActor
protocol ClipboardServing: AnyObject {
    func start(receive: @escaping @MainActor (ClipboardEntry) -> Void)
    func stop()
    func write(_ entry: ClipboardEntry) -> Bool
}

/// Original implementation informed by Maccy's change-count and excluded-type policy.
@MainActor
final class ClipboardService: ClipboardServing {
    nonisolated static let maximumEntryBytes = 4 * 1_024 * 1_024
    nonisolated static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type", "net.antelle.keeweb", "dev.ordinary.notch.clipboard"
    ]
    private let pasteboard: NSPasteboard
    private let queue = DispatchQueue(label: "ordinary.clipboard", qos: .utility)
    private var timer: Timer?
    private var lastChange = 0
    private var generation = UUID()
    private var reading = false
    private var receive: (@MainActor (ClipboardEntry) -> Void)?
    var isMonitoring: Bool { timer != nil }
    init(pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard }

    func start(receive: @escaping @MainActor (ClipboardEntry) -> Void) {
        guard timer == nil else { return }
        self.receive = receive
        lastChange = pasteboard.changeCount // Never collect the clipboard from before opt-in/resume.
        generation = UUID()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        timer.tolerance = 0.1
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }
    func stop() {
        timer?.invalidate(); timer = nil; receive = nil; generation = UUID()
    }
    func poll() {
        guard receive != nil, !reading else { return }
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        guard !IsSecureEventInputEnabled() else { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        reading = true
        let generation = generation, pasteboardName = pasteboard.name.rawValue
        queue.async { [weak self] in
            let pasteboard = NSPasteboard(name: .init(pasteboardName))
            let contents = Self.readContents(from: pasteboard)
            let entry = contents.map(ClipboardEntry.init(contents:))
            Task { @MainActor [weak self] in
                guard let self else { return }
                self.reading = false
                guard self.generation == generation, self.pasteboard.changeCount == change,
                      !IsSecureEventInputEnabled() else { return }
                if let entry { self.receive?(entry) }
            }
        }
    }
    nonisolated static func readContents(from pasteboard: NSPasteboard) -> [[String: Data]]? {
        let allTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard allTypes.isDisjoint(with: ignoredTypes), let items = pasteboard.pasteboardItems,
              !items.isEmpty, items.count <= 32 else { return nil }
        var result: [[String: Data]] = []
        var bytes = 0
        for item in items {
            guard Set(item.types.map(\.rawValue)).isDisjoint(with: ignoredTypes) else { return nil }
            var record: [String: Data] = [:]
            var types: [NSPasteboard.PasteboardType] = [.string, .URL, .fileURL, .rtf, .html]
            if item.types.contains(.png) { types.append(.png) }
            else if item.types.contains(.tiff) { types.append(.tiff) }
            for type in types where item.types.contains(type) {
                guard let data = item.data(forType: type), !data.isEmpty else { continue }
                bytes += data.count
                guard bytes <= maximumEntryBytes else { return nil }
                record[type.rawValue] = data
            }
            if record.count == 1, let data = record[NSPasteboard.PasteboardType.string.rawValue],
               String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == true { continue }
            if !record.isEmpty { result.append(record) }
        }
        return result.isEmpty ? nil : result
    }
    func write(_ entry: ClipboardEntry) -> Bool {
        let items = entry.contents.map { record in
            let item = NSPasteboardItem()
            for (type, data) in record { item.setData(data, forType: .init(type)) }
            item.setString("", forType: .init("dev.ordinary.notch.clipboard"))
            return item
        }
        pasteboard.clearContents()
        let success = pasteboard.writeObjects(items)
        lastChange = pasteboard.changeCount
        return success
    }
    deinit { timer?.invalidate() }
}
